apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-deployment
  namespace: ocr-dev
  labels:
    app: ocr-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-router
  template:
    metadata:
      labels:
        app: ocr-router
    spec:
      containers:
      - name: ocr-router-container
        # ğŸ’¡ Jenkinsì—ì„œ ë¹Œë“œ/í‘¸ì‹œí•  ì´ë¯¸ì§€ ì£¼ì†Œ
        image: 192.168.64.17:5000/ocr-router:latest 
        ports:
        - containerPort: 8000
        env:
        # ì›Œì»¤ ì„œë¹„ìŠ¤ ì ‘ê·¼ì„ ìœ„í•œ K8s ë‚´ë¶€ DNS ì„¤ì •
        - name: WORKER_A_SERVICE_URL
          value: http://worker-a-service.ocr-dev:8000
        - name: WORKER_B_SERVICE_URL
          value: http://worker-b-service.ocr-dev:8000
        - name: WORKER_C_SERVICE_URL
          value: http://worker-c-service.ocr-dev:8000
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"