apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-c-deployment
  namespace: ocr-dev
  labels:
    app: ocr-worker-c
spec:
  replicas: 1 # HPAê°€ ìµœì†Œ 1ê°œë¡œ ìœ ì§€í•¨
  selector:
    matchLabels:
      app: ocr-worker-c
  template:
    metadata:
      labels:
        app: ocr-worker-c
    spec:
      containers:
      - name: worker-c-container
        image: 192.168.64.17:5000/ocr-worker-c:latest
        ports:
        - containerPort: 8000
        env:
        # ğŸ’¡ WORKER_IDì™€ PREPROCESS_MODE ì„¤ì •
        - name: WORKER_ID
          value: "C"
        - name: TESSERACT_LANGS
          value: "eng"
        - name: PREPROCESS_MODE
          value: "COMPLEX"
        resources:
          limits:
            cpu: "2000m" # OpenCV ì—°ì‚°ì„ ìœ„í•´ CPU Limitì„ ë†’ê²Œ ì„¤ì •
          requests:
            cpu: "1000m" # HPAê°€ CPU ìš”ì²­ëŸ‰ì„ ê¸°ì¤€ìœ¼ë¡œ ìŠ¤ì¼€ì¼ë§í•¨