apiVersion: v1
kind: Service
metadata:
  name: worker-a-service
  namespace: ocr-dev
spec:
  type: ClusterIP # ğŸ’¡ í´ëŸ¬ìŠ¤í„° ë‚´ë¶€ì—ì„œë§Œ ì ‘ê·¼ (Routerì—ì„œë§Œ í˜¸ì¶œ)
  selector:
    app: ocr-worker-a
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000