apiVersion: v1
kind: Service
metadata:
  name: worker-c-service
  namespace: ocr-dev
spec:
  # ğŸ’¡ ClusterIP íƒ€ì…ìœ¼ë¡œ ì„¤ì • (í´ëŸ¬ìŠ¤í„° ë‚´ë¶€ ì „ìš©)
  type: ClusterIP 
  selector:
    app: ocr-worker-c
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000